

# This file was *autogenerated* from the file diag_complex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3)
K=QQbar

M=MatrixSpace(K,_sage_const_3 )

H=M.random_element()

print(H)
print(H.diagonalization())


