

# This file was *autogenerated* from the file t.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_10 = Integer(10); _sage_const_2 = Integer(2); _sage_const_11 = Integer(11)
k=_sage_const_3 
n=_sage_const_10 
m=_sage_const_2 
p=_sage_const_11 

q=p**m


K = GF(q, names=('t',)); (t,) = K._first_ngens(1)


V=VectorSpace(K, n)
M=MatrixSpace(K,n)

H=M.random_element()

print(H)

H1=matrix([vector(K,[c_i**p-c_i for c_i in c]) for c in H.columns()])

print(H1)
Ker=H1.left_kernel()
Ker.change_ring(GF(p))
print(Ker)
print(Ker.dimension())



