

# This file was *autogenerated* from the file RS_dec.sage
from sage.all_cmdline import *   # import sage library

_sage_const_10 = Integer(10); _sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
n=_sage_const_10 
k=_sage_const_5 

m=_sage_const_2 
p=_sage_const_2 
q=p**m

t=floor((n-k)/_sage_const_2 )

K = GF(q, names=('a',)); (a,) = K._first_ngens(1)
V=VectorSpace(K,n)

R = K['X']; (X,) = R._first_ngens(1)
x=V.random_element()
u=V.random_element()


M=matrix(K,[[u[j]*(x[i]**j) for j in range(t+_sage_const_1 )] +[-x[i]**(j) for j in range(n-t)]
		for i in range(n)])

print(M)

KER=M.right_kernel().basis()
#print(type(KER[0][:t+1]))
#Transforme une list en polynome, attention à l'ordre
P=R(list(KER[_sage_const_0 ]))

print(P)

#Q=R(list(KER[0])[t+1:])
#print(P)

