

# This file was *autogenerated* from the file tp2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_3 = Integer(3)
K = GF(_sage_const_4 , names=('t',)); (t,) = K._first_ngens(1)
R = K['X']; (X,) = R._first_ngens(1)

print(list(R.polynomials(max_degree=_sage_const_3 )))

