

# This file was *autogenerated* from the file johnson.sage
from sage.all_cmdline import *   # import sage library

_sage_const_101 = Integer(101); _sage_const_10 = Integer(10); _sage_const_100 = Integer(100); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_8 = Integer(8); _sage_const_4 = Integer(4); _sage_const_0 = Integer(0)
p=_sage_const_101 
d=_sage_const_10 

q=p**d

n=_sage_const_100 
k=n/_sage_const_2 



def rho(R):
	return float((_sage_const_1 -_sage_const_1 /q)*(_sage_const_1 -(sqrt(_sage_const_1 -(q)*(_sage_const_1 -R)/(q-_sage_const_1 )))))
def rho_asymp(R):
	return float(_sage_const_1 -sqrt(R))

def bw(R):
	return float(_sage_const_1 -sqrt(_sage_const_2 *R))

def sudan(R):
	return float(_sage_const_1 -sqrt(R)*((sqrt(R+_sage_const_8 )-sqrt(R))/_sage_const_2 ))

def gurusuami_sudan(R):
	return float(_sage_const_1 -sqrt(R)*( (sqrt(R+_sage_const_4 *d*(d+_sage_const_1 ))-sqrt(R))/(_sage_const_2 *d)))

	
g=plot(rho_asymp, _sage_const_0 , _sage_const_1 , color="purple", legend_label="rho")+plot(bw, _sage_const_0 , _sage_const_1 , color="red", legend_label="Berlekamp-Welch")+plot(sudan, _sage_const_0 , _sage_const_1 , legend_label="Sudan")+plot(gurusuami_sudan, _sage_const_0 , _sage_const_1 , legend_label="Gurusuami-Sudan", color="yellow")


g.save("johnson.png")




