

# This file was *autogenerated* from the file proba_inv.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_100000 = Integer(100000); _sage_const_1 = Integer(1)
q=_sage_const_2 
n=_sage_const_100000 
k=n

a=[_sage_const_1 -(float(_sage_const_1 /q**(n-i))) for i in range(k)]

p=product(a)

print(float(p))

