

# This file was *autogenerated* from the file test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2)
M=MatrixSpace(ZZ, _sage_const_3 )

H=M.random_element()
print(H)

print(H[[_sage_const_0 ,_sage_const_1 ,_sage_const_2 ], [_sage_const_0 ]])

